events {}

http {
	include /etc/nginx/mime.types;

	server {
		#listen 443 with SSL
		listen 443 ssl;
		listem [::]:443 ssl;

		# my domain
		server_name lantonio.42.fr

		ssl_certificate		/etc/nginx/ssl/inception.crt;
		ssl_certificate		/etc/nginx/ssl/inception.key;

		# Only TLSv1.2 ou TSLv1v3
		ssl_protocols TLSv1.2 TLSv1.3

		# Site files folsers
		root	/var/www/wordpress
		index	/index.php index.html index.html

		# Try to serve files, if not find
		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		# When find a PHP file, send to WP container
		location ~ / \.php$ {
			include			snippets/fastcgi-php.conf;
			fastcgi_paass	wordpress:9000;
		}
	}
}
